resolver: lts-9.12

packages:
- '.'
- ../shmm
- ../smol

extra-deps: 
- sparse-lin-alg-0.4.3
- vector-0.12.0.0
- shmm-1.0.0
- smol-1.0.0

flags: {}

extra-package-dbs: []

nix:
  packages: [pkgconfig, cairo, zlib, gmp, ncurses, gcc]
