resolver: lts-11.22

packages:
- '.'
- location: ../shmm
  extra-dep: true
- location: ../smol-shmm
  extra-dep: true
- location: ../smol
  extra-dep: true

extra-deps: 
- sparse-lin-alg-0.4.3
#- vector-0.12.0.0
- eigen-2.1.7
- containers-0.5.11.0
- alex-3.2.2
- happy-1.19.9

flags: {}

extra-package-dbs: []

nix:
  packages: [eigen, pkgconfig, cairo, zlib, gmp, ncurses, gcc]
